arb-dir: lib/l10n_clean
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: l10n_untranslated.txt
synthetic-package: false
nullable-getter: false
output-dir: lib/l10n_clean
