name: CI

on:
  push:
    branches: [main, master, develop, feature/**]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test --no-pub --reporter compact

      - name: Collect coverage
        run: |
          flutter test --coverage
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info || echo 'Codecov upload failed'
        if: always()
